import { error, trace } from "console";
import type { NextPage } from "next";
import Head from "next/head";
import Image from "next/image";
import React, { FormEvent, useState } from "react";
import ArticleList from "../Components/ArticleList";
import styles from "../styles/Home.module.css";

// Share Q
// Admin/quizzName/random generate Id for the q / .domain

const Home: NextPage<{ articles: string[] }> = ({ articles }) => {
  // console.log(articles);

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Quiz App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
       

        <ArticleList articles={articles} />
      </main>
    </div>
  );
};

export const getStaticProps = async () => {
  const res = await fetch(
    `https://jsonplaceholder.typicode.com/posts?_limit=5`
  );
  const articles = await res.json();
  return {
    props: {
      articles,
    },
  };
};

export default Home;
